spring:
  application:
    name: video-processor
  datasource:
    url: jdbc:postgresql://localhost:5446/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

springdoc:
  api-docs:
    swagger-ui:
      path: /swagger-ui.html

queue:
  video:
    process: videoProcessQueue

upload:
  dir: uploads

